const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..'),nodes=new Map(),calls=[];
function node(k){if(!nodes.has(k))nodes.set(k,{hidden:false,innerHTML:'',textContent:'',className:'',classList:{add(){},remove(){}},addEventListener(){},remove(){},focus(){}});return nodes.get(k)}
const catalog=fs.readFileSync(root+'/catalog-data.js','utf8').replace('export const','const');
const src=fs.readFileSync(root+'/src.js','utf8').replace(/^import .*$/gm,'');
const sample={id:'B0019',title:'Akuntansi Sektor Publik: Pengantar dan Kerangka Konseptual',author:'Data katalog rancangan',category:'Akuntansi',catalog_code:'SIM-000019',publication_year:2026,publisher:'Koleksi rancangan',shelf:'Rak A-01',replacement_value:75000,cover_path:'./covers/B0019.svg',source:'Katalog rancangan'};
const fixtures={app_role:[{role:'MEMBER'}],member:[{id:'M001',nim:'4199990001',member_no:'SIM-2026-001',name:'Nadia',email:'nadia@example.test',program:'Akuntansi',class_label:'6 PPPN-2',status:'ACTIVE'}],book:[sample],book_copy:[{barcode:'B0019-01',book_id:'B0019',status:'AVAILABLE'}],loan:[],obligation_case:[],payment:[],room_booking:[],system_parameter:[{max_loans:5,loan_days:14,late_fee_per_day:1000,room_max_minutes:120,version:1}],audit_event:[]};
async function fetch(url,opts={}){const u=new URL(url);calls.push({path:u.pathname,body:opts.body});let data;if(u.pathname.endsWith('/auth/v1/token'))data={access_token:'test-jwt',user:{id:'u1'}};else if(u.pathname.includes('/rest/v1/rpc/'))data='LN-NEW';else if(u.pathname.includes('/rest/v1/'))data=fixtures[u.pathname.split('/').pop()]||[];else throw Error('Unexpected '+url);return {ok:true,status:200,async text(){return JSON.stringify(data)},async json(){return data}}}
const context={document:{querySelector:node,addEventListener(){}},window:{scrollTo(){}},localStorage:{getItem(){return null},setItem(){}},sessionStorage:{getItem(){return null},setItem(){},removeItem(){}},crypto:globalThis.crypto,Date,Intl,Number,String,Array,Math,JSON,fetch,setTimeout,clearTimeout,setInterval,clearInterval,console};vm.createContext(context);
vm.runInContext(catalog+'\nconst SUPABASE_CONFIG={url:"https://example.supabase.co",publishableKey:"public-test-key"};\n'+src,context);
(async()=>{const result=await vm.runInContext(`(async()=>{const logged=await login('4199990001','strong-password');const count=state.books.length;await requestBook('B0019');return {logged,count,role,member:currentMember}})()`,context);assert(result.logged);assert.equal(result.count,1);assert.equal(result.member,'M001');assert(calls.some(c=>c.path.endsWith('/rpc/request_book')&&JSON.parse(c.body).p_book==='B0019'));console.log('QC koneksi Supabase: login, sinkronisasi dan RPC pengajuan terpicu');})().catch(e=>{console.error(e);process.exitCode=1});
